# Estágio de build
FROM maven:3.9-eclipse-temurin-23 AS builder

WORKDIR /app
COPY pom.xml .
# Cache das dependências
RUN mvn -B dependency:go-offline

COPY src ./src
RUN mvn -B clean package -DskipTests

# Estágio final
FROM eclipse-temurin:23-jre

WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
COPY --from=builder /app/target/classes/db/migration ./db/migration

# Variáveis de ambiente (substituídas no deploy)
ENV SPRING_DATASOURCE_URL=${DATABASE_URL}
ENV SPRING_PROFILES_ACTIVE=prod

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]